version: '3.8'
services:
  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stats

  ewm-service:
    image: amazoncorretto:11
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine